import tkinter as tk
a=tk.Tk()
a.title("Loan Calculator")
b=tk.Label(text="Annual Interest Rate")
c=tk.Label(text="Number of years")
d=tk.Label(text="Loan Amount")
e=tk.Label(text="Total Amount")
f=tk.Label(text="Monthly Amount")
g=tk.Label()
h=tk.Label()
i=tk.Entry()
j=tk.Entry()
k=tk.Entry()
def amount():
    rate=float(i.get())
    year=float(j.get())
    loan=float(k.get())
    l=loan+(loan*year*rate)/100
    g.configure(text=l)
    m=l/(12*year)
    h.configure(text=m)
n=tk.Button(text="Compute Payment",command=amount)
b.grid(row=1,column=1)
c.grid(row=2,column=1)
d.grid(row=3,column=1)
e.grid(row=4,column=1)
f.grid(row=5,column=1)
g.grid(row=4,column=2)
h.grid(row=5,column=2)
i.grid(row=1,column=2)
j.grid(row=2,column=2)
k.grid(row=3,column=2)
n.grid(row=7,column=2)
a.mainloop()

